{{- if .Values.mongodb.persistence.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "player-stats.fullname" . }}-backup
  labels:
    {{- include "player-stats.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      containers:
        - name: backup
          image: bitnami/mongodb:4.4.6-debian-10-r0
          command: ["/bin/sh", "-c"]
          args: ["cd /backup/ && mongodump -h {{ .Values.mongodb.fullnameOverride }}:{{ .Values.mongodb.service.port }}"]
          volumeMounts:
            - name: backup
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.fullnameOverride }}-data-backup-{{ sub .Release.Revision 1 }}
{{- end }}
